name: Node.js 18.x, 20.x build

on:
  push:
    branches: [master, feat/v2.0]

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: testbuilds
      cancel-in-progress: false

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

      - name: Update Coverage Badge
        uses: we-cli/coverage-badge-action@main
