name: Node.js 18.x, 20.x build

on:
  push:
    branches: [master, feat/v2.0]

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: testbuilds
      cancel-in-progress: false

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build
      - run: npm run test

      - name: Get npm version
        id: get-values
        shell: bash
        run: |
          VERSION=$(node -p 't=require(`./package.json`).version')
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Update Coverage Badge
        uses: markusberg/coverage-badge-action@main
        with:
          version: ${{ steps.get-values.outputs.VERSION }}
